version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:10000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - PORT=10000
        volumes:
            - ./temp_codes:/app/temp_codes
        restart: always
