import { useState, useEffect, useCallback, useRef } from "react";
import { generateWordId, getWordCategories } from "@/lib/api/pastes";
import { toast } from "@/components/ui/toast";

export type WordPreset = "classic" | "aesthetic" | "scifi" | "world" | "custom";

export interface PresetConfig {
	id: WordPreset;
	label: string;
	icon: string;
	categories: string[];
}

export const WORD_PRESETS: PresetConfig[] = [
	{
		id: "classic",
		label: "Classic",
		icon: "🦊",
		categories: ["adjectives", "animals"],
	},
	{
		id: "aesthetic",
		label: "Aesthetic",
		icon: "🎨",
		categories: ["colors", "animals"],
	},
	{
		id: "scifi",
		label: "Sci-Fi",
		icon: "⭐",
		categories: ["adjectives", "starWars"],
	},
	{
		id: "world",
		label: "World",
		icon: "🌍",
		categories: ["adjectives", "countries"],
	},
];

export const CATEGORY_METADATA: Record<
	string,
	{ label: string; icon: string }
> = {
	animals: { label: "Animals", icon: "🦊" },
	colors: { label: "Colors", icon: "🎨" },
	adjectives: { label: "Adjectives", icon: "✨" },
	countries: { label: "Countries", icon: "🌍" },
	names: { label: "Names", icon: "👤" },
	starWars: { label: "Sci-Fi", icon: "⭐" },
	languages: { label: "Languages", icon: "🗣️" },
};

export const useSemanticGenerator = (
	setCustomId: (v: string) => void,
	currentId?: string,
) => {
	const [wordCount, setWordCount] = useState(2);
	const [includeNumber, setIncludeNumber] = useState(false);
	const [activePreset, setActivePreset] = useState<WordPreset>("classic");
	const [categories, setCategories] = useState<string[]>([]);
	const [selectedCats, setSelectedCats] = useState<string[]>([
		"adjectives",
		"animals",
	]);
	const [isGenerating, setIsGenerating] = useState(false);
	const hasAutoGenerated = useRef(false);

	useEffect(() => {
		const fetchCategories = async () => {
			try {
				const { categories: fetchedCats } = await getWordCategories();
				setCategories(fetchedCats);
			} catch (error) {
				console.error("Failed to fetch word categories:", error);
			}
		};
		fetchCategories();
	}, []);

	const handleGenerate = useCallback(
		async (
			overrideCount?: number,
			overrideCats?: string[],
			overrideNumber?: boolean,
		) => {
			setIsGenerating(true);
			try {
				const countToUse = overrideCount ?? wordCount;
				const catsToUse = overrideCats ?? selectedCats;
				const numberToUse = overrideNumber ?? includeNumber;

				const { id } = await generateWordId(
					countToUse,
					catsToUse,
					numberToUse,
				);
				setCustomId(id);
			} catch (error) {
				console.error("Failed to generate semantic ID:", error);
				toast.add({ title: "Failed to generate words", type: "error" });
			} finally {
				setIsGenerating(false);
			}
		},
		[wordCount, selectedCats, includeNumber, setCustomId],
	);

	// Auto-generate on first mount if input is empty
	useEffect(() => {
		if (!hasAutoGenerated.current && !currentId?.trim()) {
			hasAutoGenerated.current = true;
			handleGenerate(2, ["adjectives", "animals"], false);
		}
	}, [currentId, handleGenerate]);

	const applyPreset = (presetId: WordPreset) => {
		setActivePreset(presetId);
		if (presetId === "custom") return;

		const preset = WORD_PRESETS.find((p) => p.id === presetId);
		if (preset) {
			setSelectedCats(preset.categories);
			handleGenerate(wordCount, preset.categories, includeNumber);
		}
	};

	const toggleCategory = (cat: string) => {
		setActivePreset("custom");
		setSelectedCats((prev) => {
			const next = prev.includes(cat)
				? prev.filter((c) => c !== cat)
				: [...prev, cat];
			return next.length === 0 ? [cat] : next;
		});
	};

	return {
		wordCount,
		setWordCount,
		includeNumber,
		setIncludeNumber,
		activePreset,
		applyPreset,
		categories,
		selectedCats,
		isGenerating,
		handleGenerate,
		toggleCategory,
	};
};
